version: '3.9'

services:
  redis:
    image: redis/redis-stack-server
    restart: always
    # This persistence strategy saves a snapshot of the DB
    # every 60 seconds if at least 1 write operation was performed
    command: redis-server --save 60 1 --loglevel warning --protected-mode no  
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so
      --loadmodule /opt/redis-stack/lib/redistimeseries.so
    volumes:
      - .redis-data:/data
    ports:
      - 6379:6379

  redis-insight:
    image: redis/redisinsight
    ports:
      - 8001:5540
